name: auto testing
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    container: ghcr.io/hazuki3417/verify-ci-cd-php-fpm:latest

    services:
      verify-ci-cd-mongo:
        image: ghcr.io/hazuki3417/verify-ci-cd-mongo:latest
      # verify-ci-cd-php-fpm:
      #   image: ghcr.io/hazuki3417/verify-ci-cd-php-fpm:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      -
        run: docker ps -a

      -
        run: php -v



# deploy-api-image-ghcr:
#   runs-on: ubuntu-latest
#   env:
#     BASE_BRANCH: main
#     IMAGE_OWNER: hazuki3417
#     IMAGE_NAME: testing-file-generator-api

#   steps:
#     - uses: actions/checkout@v2
#       with:
#         ref: ${{ env.BASE_BRANCH }}

#     - name: Set GITHUB_ENV
#       run: |
#         echo ${{ github.event.release.tag_name }} | sed -E 's/v([0-9]+.[0-9]+.[0-9]+)/RELEASE_VERSION=\1/i' >> $GITHUB_ENV
#     - name: Build image
#       run: make build -e IMAGE_NAME=${{ env.IMAGE_NAME }}

#     - name: Set image tag
#       run: make set-tag-ghcr -e IMAGE_OWNER=${{ env.IMAGE_OWNER }} IMAGE_NAME=${{ env.IMAGE_NAME }} RELEASE_VERSION=${{ env.RELEASE_VERSION }}

#     - name: Login GitHub Container Registry
#       run: make login-ghcr -e PAT_GITHUB=${{ secrets.PAT_FOR_GITHUB }} GITHUB_USER=${{ env.IMAGE_OWNER }}

#     - name: Push GitHub Container Registry
#       run: make push-ghcr -e IMAGE_OWNER=${{ env.IMAGE_OWNER }} IMAGE_NAME=${{ env.IMAGE_NAME }} RELEASE_VERSION=${{ env.RELEASE_VERSION }}
